FROM node:<%= upstream.node_version %>-alpine

RUN apk update \
&& apk --no-cache --update add \
  build-base nodejs tzdata

WORKDIR /opt/app
COPY . .

ENV NODE_ENV=production
<%- if upstream.dockerfile %>
<%= upstream.dockerfile.strip %>
<%- end %>
RUN npm install
CMD ["npm", "start"]
