FROM ruby:<%= upstream.ruby_version %>-alpine

RUN apk update \
&& apk --no-cache --update add \
  build-base nodejs tzdata \
  mysql-dev mysql-client --no-install-recommends \
  postgresql-dev postgresql-client \
  libxslt-dev libxml2-dev

WORKDIR /opt/app
COPY . .

EXPOSE <%= upstream.port %>

ENV RAILS_ENV=production
<%- if upstream.dockerfile %>
<%= upstream.dockerfile.strip %>
<%- end %>
RUN gem install bundler -v <%= upstream.bundler_version %>
RUN bundle install --without development test
CMD ["rm", "-f", "tmp/pids/server.pid"]
CMD ["rails", "server", "-b", "0.0.0.0"]
