FROM ruby:<%= upstream.ruby_version %>-alpine

RUN apk update \
&& apk --no-cache --update add \
  build-base nodejs tzdata \
  mysql-dev mysql-client --no-install-recommends \
  postgresql-dev postgresql-client \
  libxslt-dev libxml2-dev

WORKDIR /opt/app
COPY . .

ENV RACK_ENV=production
RUN gem install bundler -v <%= upstream.bundler_version %>
RUN bundle install --without development test
CMD ["bundle", "exec", "rackup", "config.ru", "-o", "0.0.0.0"]
