---
source:
  - http://dimafeng.com/2015/10/17/docker-distribution/
constants:
  image_tag: vps_docker_image
  zip_file: vps_docker_image.gzip
tasks:
  - description: Building docker image
    task: execute
    command: docker build --no-cache -t {{ image_tag }} .
  - description: Saving docker image as .gzip file
    task: execute
    command: docker save {{ image_tag }} | gzip > /tmp/{{ zip_file }}
  - description: Server copying {{ zip_file }}
    task: execute
    command: scp /tmp/{{ zip_file }} {{ host }}:/tmp/{{ zip_file }} > /dev/tty
  - description: Stopping current containers
    task: remote_execute
    command: cd /tmp && docker-compose stop
  - description: Removing current container
    task: remote_execute
    command: docker container rm $(docker container ls -f ancestor={{ image_tag }} -aq)
  - description: Removing current image
    task: remote_execute
    command: docker image rm {{ image_tag }}
  - description: Unzipping and loading docker image
    task: remote_execute
    command: gunzip < /tmp/{{ zip_file }} | docker load
  - description: Server copying docker-compose.yml
    task: execute
    command: scp docker-compose.yml {{ host }}:/tmp/docker-compose.yml > /dev/tty
  - description: Starting containers
    task: remote_execute
    command: cd /tmp && docker-compose up -d
  - description: Checking running docker images
    task: remote_execute
    command: docker ps
