---
source:
  https://www.digitalocean.com/community/tutorials/initial-server-setup-with-ubuntu-18-04
tasks:
  - task: :confirm
    question: Do you want to create a sudo user?
    y:
      - task: input
        question: Fill in the username for the new sudo user
        as: username
