---
description:
  Deploy web application to the server
usage:
  deploy HOST [TOOL]
arguments:
  - host
  - tool
options:
  s:
    type: array
    aliases: skip-build
    default: []
tasks:
  - task: ensure
    argument: user
    fallbacks:
      - task: read_config
        key: user
      - description: Obtaining remote user
        task: remote_execute
        command: whoami
  - task: ensure
    argument: tool
    fallbacks:
      - task: read_config
        key: tool
      - description: Choose which deploy tool to use
        task: select
        question: Which deployment tool do you want to use?
        options: << playbooks >>
  - task: ensure
    argument: release_path
    fallbacks:
      - task: read_config
        key: release_path
      - description: Specify which directory to deploy to
        task: input
        question: Enter release path on the server
        default: ~/app
  - task: write_config
    config:
      user: << user >>
      tool: << tool >>
      release_path: << release_path >>
  - task: obtain_config
  - task: playbook
    playbook: deploy/{{ tool }}
