---
description:
  Deploy web application to the server
usage:
  deploy HOST [TOOL]
arguments:
  - host
  - tool
tasks:
  - task: ensure
    argument: tool
    fallbacks:
      - task: read_config
        key: tool
      - description: Choose which deploy tool to use
        task: select
        question: Which deployment tool do you want to use?
        options: << playbooks >>
  - task: write_config
    config:
      user: << user >>
      tool: << tool >>
      release_path:
        type: input
        question: Enter release path on the server
        default: ~/app
  - task: playbook
    playbook: deploy/{{ tool }}
